import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'admin' at '12/8/17 2:54 PM' with Gradle 3.2
 *
 * @author admin, @date 12/8/17 2:54 PM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
       // Library classUnderTest = new Library();
        //assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
