#spring:
#  profiles: development
#server:#  port: 5050
  
#---
#spring:
#  profiles: production
#server:
#  port: 9090
#---
#spring:
#  profiles: testing
#server:
#  port: 2020

management:
  endpoints:
    web:
     exposure:
      include: '*'
  endpoint:
    health:
     show-details: always
    beans:
     enabled: true 
       
  

    