/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GradlePrj1;

public class Library {
	
	public static void main(String[] args) {
		System.out.println("hello gradle");
	}
    public boolean someLibraryMethod() {
        return true;
    }
  public  void  addition(int a, int b) {
    	System.out.println("sum is "+(a+b));
    }
}
