spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create # Options: none, create-only, drop, create, validate, update
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 7070

