"use strict";
exports.__esModule = true;
var BasicPhone_1 = require("./BasicPhone");
var SmartPhone_1 = require("./SmartPhone");
var bPhone = new BasicPhone_1.BasicPhone(55656566, "nokia basic 105 ", 6677, "basicType");
bPhone.printMobileDetail();
console.log('type ' + bPhone.mobileType);
var sPhone = new SmartPhone_1.SmartPhone(55656567, "samsung pro7 ", 6677, "SmartPhone");
sPhone.printMobileDetail();
console.log('type ' + bPhone.mobileType);
