# Porta
server.port=8080

# Configura��o do banco Oracle
# spring.datasource.url=jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
# spring.datasource.username=rm99657
# spring.datasource.password=150903
# spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.datasource.url=jdbc:mysql://localhost:3306/db1
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver



# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Timezone & Jackson
spring.jackson.time-zone=America/Sao_Paulo
spring.jackson.serialization.write-dates-as-timestamps=false

# JWT
security.jwt.secret=Ih3R6Z8G7O9P2Q4T6V8X0a2c4e6g8i0k2m4o6q8s0u2w4y6A
security.jwt.expiration-millis=3600000

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
