spring.application.name=spring_jwt_auth
jwt.secret=0nvPwUd99WurJBy3ioP4dh9e06rGWGgZYxsRURFWnBtL/Kx8kBemj3kRR/RAqMa4
spring.application.name=spring-restapi
spring.datasource.url=jdbc:mysql://localhost:3306/mydatabase?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


