
package com.cts.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.2.0
 * 2026-04-22T16:40:08.030+05:30
 * Generated source version: 4.2.0
 *
 */
public final class Calculator_CalculatorImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://webservice.cts.com/", "CalculatorImplService");

    private Calculator_CalculatorImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CalculatorImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URI(args[0]).toURL();
                }
            } catch (URISyntaxException e) {
                e.printStackTrace();
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        CalculatorImplService ss = new CalculatorImplService(wsdlURL, SERVICE_NAME);
        Calculator port = ss.getCalculatorImplPort();

        {
        System.out.println("Invoking sub...");
        int _sub_firstno = 0;
        int _sub_secondno = 0;
        int _sub__return = port.sub(_sub_firstno, _sub_secondno);
        System.out.println("sub.result=" + _sub__return);


        }
        {
        System.out.println("Invoking division...");
        int _division_arg0 = 0;
        int _division_arg1 = 0;
        try {
            int _division__return = port.division(_division_arg0, _division_arg1);
            System.out.println("division.result=" + _division__return);

        } catch (DivisionException_Exception e) {
            System.out.println("Expected exception: DivisionException has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking addition...");
        int _addition_arg0 = 0;
        int _addition_arg1 = 0;
        int _addition__return = port.addition(_addition_arg0, _addition_arg1);
        System.out.println("addition.result=" + _addition__return);


        }

        System.exit(0);
    }

}
