package com.cts.webservice;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.2.0
 * 2026-04-22T16:40:08.339+05:30
 * Generated source version: 4.2.0
 *
 */
@WebService(targetNamespace = "http://webservice.cts.com/", name = "Calculator")
@XmlSeeAlso({ObjectFactory.class})
public interface Calculator {

    @WebMethod
    @Action(input = "http://webservice.cts.com/Calculator/subRequest", output = "http://webservice.cts.com/Calculator/subResponse")
    @RequestWrapper(localName = "sub", targetNamespace = "http://webservice.cts.com/", className = "com.cts.webservice.Sub")
    @ResponseWrapper(localName = "subResponse", targetNamespace = "http://webservice.cts.com/", className = "com.cts.webservice.SubResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int sub(

        @WebParam(name = "firstno", targetNamespace = "")
        int firstno,
        @WebParam(name = "secondno", targetNamespace = "")
        int secondno
    );

    @WebMethod
    @Action(input = "http://webservice.cts.com/Calculator/divisionRequest", output = "http://webservice.cts.com/Calculator/divisionResponse", fault = {@FaultAction(className = DivisionException_Exception.class, value = "http://webservice.cts.com/Calculator/division/Fault/DivisionException")})
    @RequestWrapper(localName = "division", targetNamespace = "http://webservice.cts.com/", className = "com.cts.webservice.Division")
    @ResponseWrapper(localName = "divisionResponse", targetNamespace = "http://webservice.cts.com/", className = "com.cts.webservice.DivisionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int division(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    ) throws DivisionException_Exception;

    @WebMethod
    @Action(input = "http://webservice.cts.com/Calculator/additionRequest", output = "http://webservice.cts.com/Calculator/additionResponse")
    @RequestWrapper(localName = "addition", targetNamespace = "http://webservice.cts.com/", className = "com.cts.webservice.Addition")
    @ResponseWrapper(localName = "additionResponse", targetNamespace = "http://webservice.cts.com/", className = "com.cts.webservice.AdditionResponse")
    @WebResult(name = "return", targetNamespace = "")
    public int addition(

        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1
    );
}
