
package com.cts.webservice;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.2.0
 * 2026-04-22T16:40:08.320+05:30
 * Generated source version: 4.2.0
 */

@WebFault(name = "DivisionException", targetNamespace = "http://webservice.cts.com/")
public class DivisionException_Exception extends Exception {

    private com.cts.webservice.DivisionException faultInfo;

    public DivisionException_Exception() {
        super();
    }

    public DivisionException_Exception(String message) {
        super(message);
    }

    public DivisionException_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public DivisionException_Exception(String message, com.cts.webservice.DivisionException divisionException) {
        super(message);
        this.faultInfo = divisionException;
    }

    public DivisionException_Exception(String message, com.cts.webservice.DivisionException divisionException, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = divisionException;
    }

    public com.cts.webservice.DivisionException getFaultInfo() {
        return this.faultInfo;
    }
}
