spring.security.oauth2.client.registration.github.client-id=token2
spring.security.oauth2.client.registration.github.client-secret=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_123
spring.security.oauth2.client.registration.github.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.github.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.github.scope=openid,profile,email
