package com.cts.webservice;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.2.0
 * 2026-04-22T16:40:08.367+05:30
 * Generated source version: 4.2.0
 *
 */
@WebServiceClient(name = "CalculatorImplService",
                  wsdlLocation = "http://localhost:8080/Calcws/calc?wsdl",
                  targetNamespace = "http://webservice.cts.com/")
public class CalculatorImplService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://webservice.cts.com/", "CalculatorImplService");
    public static final QName CalculatorImplPort = new QName("http://webservice.cts.com/", "CalculatorImplPort");
    static {
        URL url = null;
        try {
            url = URI.create("http://localhost:8080/Calcws/calc?wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CalculatorImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/Calcws/calc?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CalculatorImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CalculatorImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatorImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CalculatorImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CalculatorImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CalculatorImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Calculator
     */
    @WebEndpoint(name = "CalculatorImplPort")
    public Calculator getCalculatorImplPort() {
        return super.getPort(CalculatorImplPort, Calculator.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Calculator
     */
    @WebEndpoint(name = "CalculatorImplPort")
    public Calculator getCalculatorImplPort(WebServiceFeature... features) {
        return super.getPort(CalculatorImplPort, Calculator.class, features);
    }

}
