/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JavaEx1;

public class Library {

	public static void main(String[] args) {
		System.out.println("hello world");
	}

	public boolean someLibraryMethod() {
		return true;
	}
}
