spring.application.name=spring-boot-ex1

spring.datasource.url=jdbc:postgresql://localhost:5432/db2
spring.datasource.username=postgres
spring.datasource.password=postgresql

spring.datasource.driver-class-name=org.postgresql.Driver
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

#spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

