
package com.cts.dao;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.2.0
 * 2026-04-24T12:09:09.497+05:30
 * Generated source version: 4.2.0
 *
 */
public final class CustomerDaoImpl_CustomerDaoImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://dao.cts.com/", "CustomerDaoImplService");

    private CustomerDaoImpl_CustomerDaoImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CustomerDaoImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URI(args[0]).toURL();
                }
            } catch (URISyntaxException e) {
                e.printStackTrace();
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        CustomerDaoImplService ss = new CustomerDaoImplService(wsdlURL, SERVICE_NAME);
        CustomerDaoImpl port = ss.getCustomerDaoImplPort();

        {
        System.out.println("Invoking addCustomer...");
        com.cts.dao.Customer _addCustomer_arg0 = null;
        try {
            boolean _addCustomer__return = port.addCustomer(_addCustomer_arg0);
            System.out.println("addCustomer.result=" + _addCustomer__return);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }
        {
        System.out.println("Invoking getAllCustomer...");
        try {
            java.util.List<com.cts.dao.Customer> _getAllCustomer__return = port.getAllCustomer();
            System.out.println("getAllCustomer.result=" + _getAllCustomer__return);

        } catch (Exception_Exception e) {
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }

            }

        System.exit(0);
    }

}
