package com.cts.dao;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.FaultAction;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.2.0
 * 2026-04-24T12:09:09.608+05:30
 * Generated source version: 4.2.0
 *
 */
@WebService(targetNamespace = "http://dao.cts.com/", name = "CustomerDaoImpl")
@XmlSeeAlso({ObjectFactory.class})
public interface CustomerDaoImpl {

    @WebMethod
    @Action(input = "http://dao.cts.com/CustomerDaoImpl/addCustomerRequest", output = "http://dao.cts.com/CustomerDaoImpl/addCustomerResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://dao.cts.com/CustomerDaoImpl/addCustomer/Fault/Exception")})
    @RequestWrapper(localName = "addCustomer", targetNamespace = "http://dao.cts.com/", className = "com.cts.dao.AddCustomer")
    @ResponseWrapper(localName = "addCustomerResponse", targetNamespace = "http://dao.cts.com/", className = "com.cts.dao.AddCustomerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public boolean addCustomer(

        @WebParam(name = "arg0", targetNamespace = "")
        com.cts.dao.Customer arg0
    ) throws Exception_Exception;

    @WebMethod
    @Action(input = "http://dao.cts.com/CustomerDaoImpl/getAllCustomerRequest", output = "http://dao.cts.com/CustomerDaoImpl/getAllCustomerResponse", fault = {@FaultAction(className = Exception_Exception.class, value = "http://dao.cts.com/CustomerDaoImpl/getAllCustomer/Fault/Exception")})
    @RequestWrapper(localName = "getAllCustomer", targetNamespace = "http://dao.cts.com/", className = "com.cts.dao.GetAllCustomer")
    @ResponseWrapper(localName = "getAllCustomerResponse", targetNamespace = "http://dao.cts.com/", className = "com.cts.dao.GetAllCustomerResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.cts.dao.Customer> getAllCustomer()
 throws Exception_Exception;
}
