package com.cts.dao;

import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceFeature;
import jakarta.xml.ws.Service;

/**
 * This class was generated by Apache CXF 4.2.0
 * 2026-04-24T12:09:09.616+05:30
 * Generated source version: 4.2.0
 *
 */
@WebServiceClient(name = "CustomerDaoImplService",
                  wsdlLocation = "http://shankar:8080/JaxwsDb1/customer?wsdl",
                  targetNamespace = "http://dao.cts.com/")
public class CustomerDaoImplService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://dao.cts.com/", "CustomerDaoImplService");
    public static final QName CustomerDaoImplPort = new QName("http://dao.cts.com/", "CustomerDaoImplPort");
    static {
        URL url = null;
        try {
            url = URI.create("http://shankar:8080/JaxwsDb1/customer?wsdl").toURL();
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CustomerDaoImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://shankar:8080/JaxwsDb1/customer?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CustomerDaoImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CustomerDaoImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerDaoImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CustomerDaoImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CustomerDaoImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CustomerDaoImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CustomerDaoImpl
     */
    @WebEndpoint(name = "CustomerDaoImplPort")
    public CustomerDaoImpl getCustomerDaoImplPort() {
        return super.getPort(CustomerDaoImplPort, CustomerDaoImpl.class);
    }

    /**
     *
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerDaoImpl
     */
    @WebEndpoint(name = "CustomerDaoImplPort")
    public CustomerDaoImpl getCustomerDaoImplPort(WebServiceFeature... features) {
        return super.getPort(CustomerDaoImplPort, CustomerDaoImpl.class, features);
    }

}
