
package com.cts.dao;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 4.2.0
 * 2026-04-24T12:09:09.599+05:30
 * Generated source version: 4.2.0
 */

@WebFault(name = "Exception", targetNamespace = "http://dao.cts.com/")
public class Exception_Exception extends java.lang.Exception {

    private com.cts.dao.Exception faultInfo;

    public Exception_Exception() {
        super();
    }

    public Exception_Exception(String message) {
        super(message);
    }

    public Exception_Exception(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.cts.dao.Exception exception) {
        super(message);
        this.faultInfo = exception;
    }

    public Exception_Exception(String message, com.cts.dao.Exception exception, java.lang.Throwable cause) {
        super(message, cause);
        this.faultInfo = exception;
    }

    public com.cts.dao.Exception getFaultInfo() {
        return this.faultInfo;
    }
}
