
package org.com.dao;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CustomerDaoImplService", targetNamespace = "http://dao.com.org/", wsdlLocation = "http://localhost:9090/SoapCrud/abc?wsdl")
public class CustomerDaoImplService
    extends Service
{

    private final static URL CUSTOMERDAOIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CUSTOMERDAOIMPLSERVICE_EXCEPTION;
    private final static QName CUSTOMERDAOIMPLSERVICE_QNAME = new QName("http://dao.com.org/", "CustomerDaoImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9090/SoapCrud/abc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMERDAOIMPLSERVICE_WSDL_LOCATION = url;
        CUSTOMERDAOIMPLSERVICE_EXCEPTION = e;
    }

    public CustomerDaoImplService() {
        super(__getWsdlLocation(), CUSTOMERDAOIMPLSERVICE_QNAME);
    }

    public CustomerDaoImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMERDAOIMPLSERVICE_QNAME, features);
    }

    public CustomerDaoImplService(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMERDAOIMPLSERVICE_QNAME);
    }

    public CustomerDaoImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMERDAOIMPLSERVICE_QNAME, features);
    }

    public CustomerDaoImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomerDaoImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CustomerDaoImpl
     */
    @WebEndpoint(name = "CustomerDaoImplPort")
    public CustomerDaoImpl getCustomerDaoImplPort() {
        return super.getPort(new QName("http://dao.com.org/", "CustomerDaoImplPort"), CustomerDaoImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomerDaoImpl
     */
    @WebEndpoint(name = "CustomerDaoImplPort")
    public CustomerDaoImpl getCustomerDaoImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://dao.com.org/", "CustomerDaoImplPort"), CustomerDaoImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMERDAOIMPLSERVICE_EXCEPTION!= null) {
            throw CUSTOMERDAOIMPLSERVICE_EXCEPTION;
        }
        return CUSTOMERDAOIMPLSERVICE_WSDL_LOCATION;
    }

}
