
package org.com.dao;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomerDaoImpl", targetNamespace = "http://dao.com.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomerDaoImpl {


    /**
     * 
     * @return
     *     returns java.util.List<org.com.dao.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "showAllCustomer", targetNamespace = "http://dao.com.org/", className = "org.com.dao.ShowAllCustomer")
    @ResponseWrapper(localName = "showAllCustomerResponse", targetNamespace = "http://dao.com.org/", className = "org.com.dao.ShowAllCustomerResponse")
    @Action(input = "http://dao.com.org/CustomerDaoImpl/showAllCustomerRequest", output = "http://dao.com.org/CustomerDaoImpl/showAllCustomerResponse")
    public List<Customer> showAllCustomer();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeCustomer", targetNamespace = "http://dao.com.org/", className = "org.com.dao.RemoveCustomer")
    @ResponseWrapper(localName = "removeCustomerResponse", targetNamespace = "http://dao.com.org/", className = "org.com.dao.RemoveCustomerResponse")
    @Action(input = "http://dao.com.org/CustomerDaoImpl/removeCustomerRequest", output = "http://dao.com.org/CustomerDaoImpl/removeCustomerResponse")
    public boolean removeCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        Customer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCustomer", targetNamespace = "http://dao.com.org/", className = "org.com.dao.AddCustomer")
    @ResponseWrapper(localName = "addCustomerResponse", targetNamespace = "http://dao.com.org/", className = "org.com.dao.AddCustomerResponse")
    @Action(input = "http://dao.com.org/CustomerDaoImpl/addCustomerRequest", output = "http://dao.com.org/CustomerDaoImpl/addCustomerResponse")
    public boolean addCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        Customer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateCustomer", targetNamespace = "http://dao.com.org/", className = "org.com.dao.UpdateCustomer")
    @ResponseWrapper(localName = "updateCustomerResponse", targetNamespace = "http://dao.com.org/", className = "org.com.dao.UpdateCustomerResponse")
    @Action(input = "http://dao.com.org/CustomerDaoImpl/updateCustomerRequest", output = "http://dao.com.org/CustomerDaoImpl/updateCustomerResponse")
    public boolean updateCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        Customer arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns org.com.dao.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "searchCustomer", targetNamespace = "http://dao.com.org/", className = "org.com.dao.SearchCustomer")
    @ResponseWrapper(localName = "searchCustomerResponse", targetNamespace = "http://dao.com.org/", className = "org.com.dao.SearchCustomerResponse")
    @Action(input = "http://dao.com.org/CustomerDaoImpl/searchCustomerRequest", output = "http://dao.com.org/CustomerDaoImpl/searchCustomerResponse")
    public Customer searchCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        Customer arg0);

}
