spring:
  jpa:
    show-sql:  true
    hibernate:
#      ddl-auto:  create
  datasource:
    url: jdbc:mysql://localhost:3306/db4
    username:  root
    password:  mysql
    driver-class-name:  com.mysql.cj.jdbc.Driver
