spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23li1tYG4G4YEFmsn7
            client-secret: d98e16a55f4ee54e349af77a28ec40c252cafca9
            scope: read:user
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: GitHub
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: login
