<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.cts</groupId>
  <artifactId>JaxWsDb1WebClient</artifactId>
  <packaging>war</packaging>
  <version>0.0.1-SNAPSHOT</version>
  <name>JaxWsDb1WebClient Maven Webapp</name>
  <url>http://maven.apache.org</url>
  <dependencies>
  <dependency>
	    <groupId>jakarta.servlet</groupId>
	    <artifactId>jakarta.servlet-api</artifactId>
	    <version>6.1.0</version>
	    <scope>provided</scope>
	</dependency>
	
   <dependency>
	    <groupId>com.sun.xml.ws</groupId>
	    <artifactId>jaxws-rt</artifactId>
	    <version>4.0.1</version>
	    <scope>compile</scope>
	</dependency>

  </dependencies>
  <build>
    <finalName>JaxWsDb1WebClient</finalName>
  </build>
</project>
