/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package JavaEx1;

import org.junit.*;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
