##spring.jpa.hibernate.ddl-auto=create
#spring.datasource.url=jdbc:mysql://localhost:3306/db9
#spring.datasource.username=root
#spring.datasource.password=root
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql=true
#
#
#spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
#
##logging.file.name=log/person.log
#
#
