<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/user"
	xmlns:tns="http://www.example.org/user" elementFormDefault="qualified">
	<xsd:element name="note">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="to">
					<xsd:complexType>
						<xsd:attribute name="id">

						</xsd:attribute>
					</xsd:complexType>

				</xsd:element>
				<xsd:element name="from" type="xsd:string">
				</xsd:element>
				<xsd:element name="date" type="xsd:date">
				</xsd:element>
				<xsd:element name="subject" type="xsd:string">
				</xsd:element>

				<xsd:element name="pin" type="xsd:integer">
				</xsd:element>


			</xsd:sequence>

		</xsd:complexType>

	</xsd:element>








</xsd:schema>