@startuml
 abstract class Customer {
  private int id;
  private String name;
}
class CustomerMain {
}
class CustomerService{
}
class SpecialCustomer extends  Customer {
    @PostConstruct
    public void init(){}
}
class RegularCustomer extends  Customer {
    @PostConstruct
    public void init(){
    }
}
@enduml