/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'admin' at '11/29/17 5:11 PM' with Gradle 3.2
 *
 * @author admin, @date 11/29/17 5:11 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
