spring.application.name=medblockapp
server.port=8080

# Google OAuth2 Credentials
#spring.security.oauth2.client.registration.google.client-id=Ov23li1tYG4G4YEFmsn7
#spring.security.oauth2.client.registration.google.client-secret=d98e16a55f4ee54e349af77a28ec40c252cafca9

spring.security.oauth2.client.registration.github.client-id=Ov23li1tYG4G4YEFmsn7
spring.security.oauth2.client.registration.github.client-secret=d98e16a55f4ee54e349af77a28ec40c252cafca9




# Scopes to request from the user
spring.security.oauth2.client.registration.github.scope=openid,profile,email



logging.level.org.springframework.security=DEBUG