package ws;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 4.2.0
 * 2026-04-20T17:27:35.542+05:30
 * Generated source version: 4.2.0
 *
 */
@WebService(targetNamespace = "http://ws.example.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebMethod
    @Action(input = "http://ws.example.com/HelloWorld/sayHelloRequest", output = "http://ws.example.com/HelloWorld/sayHelloResponse")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ws.example.com/", className = "ws.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ws.example.com/", className = "ws.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHello(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
