spring:
  datasource:
    url:  jdbc:mysql://localhost/coforge
    driverClassName:  com.mysql.jdbc.Driver
    username:  root
    password:  mysql
  jpa:
    show-sql:  true
    database-platform:  org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto:  update
  h2:
    console:
      enabled:  true
      path:  /h2-console
  application:
    name: OneToOneProd
server:
  port:  9090

