spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
#              uri: lb://USER-SERVICE
              uri: http://localhost:8086
              predicates:
                - Path=/client/**

server:
  port: 9056
#== server.port
