@startuml
 class Person {
    protected int personId;
    protected  String  personName;
    protected  float personSalary;
    void personInfo()
}
class  Employee extends  Person{
}
class Manager extends Person{
    private String location;
    private String companyName;
    private int age;
    private float pf;

   public   String getLocation()
    public  String getCompanyName()
    public int getAge()

    public float getPf()

    public Manager(String location, String companyName, int age, float pf)



}

@enduml