
package com.abc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Welcome", targetNamespace = "http://abc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Welcome {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://abc.com/", className = "com.abc.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://abc.com/", className = "com.abc.HelloResponse")
    @Action(input = "http://abc.com/Welcome/helloRequest", output = "http://abc.com/Welcome/helloResponse")
    public String hello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "factorial", targetNamespace = "http://abc.com/", className = "com.abc.Factorial")
    @ResponseWrapper(localName = "factorialResponse", targetNamespace = "http://abc.com/", className = "com.abc.FactorialResponse")
    @Action(input = "http://abc.com/Welcome/factorialRequest", output = "http://abc.com/Welcome/factorialResponse")
    public int factorial(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
