server:
    port:  9090
spring:
  datasource:
    url:  jdbc:mysql://localhost:3306/db1
    username:  root
    password:  mysql
  mvc:
    view:
      prefix:  /WEB-INF/jsp/
      suffix:  .jsp
hibernate:
  dialect:  org.hibernate.dialect.MySQL5Dialect
  show_sql:  true
   
    
