#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
#spring.jpa.show-sql=true

spring.h2.console.path=/h2-console

spring.datasource.url=jdbc:mysql://localhost:3306/db9
spring.datasource.username=root
spring.datasource.password=root

# JPA/Hibernate Configuration (Optional but commonly used with MySQL)
spring.jpa.hibernate.ddl-auto=create
//spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.servlet.context-path=/employee-service
addressservice.base.url=http://localhost:8081/address-service

spring.application.name=employee-service
server.port=8080