/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'admin' at '12/7/17 4:46 AM' with Gradle 3.2
 *
 * @author admin, @date 12/7/17 4:46 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
