spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db9
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
