#  spring.datasource.url=jdbc:hsqldb:mem:testdb
#    spring.datasource.username=SA
#    spring.datasource.password=
#    spring.datasource.driver-class-name=org.hsqldb.jdbc.JDBCDriver
#

spring:
  application:
    name: spring-test-qatesting
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
#  datasource:
#    url: jdbc:hsqldb:mem:testdb
#    username: sa
#    password: root
#    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 5050